FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk"

RUN apt-get update \
&& apt-get install -y git make perl curl \
&& git clone https://github.com/marbl/Krona \
&& mkdir -p Krona/KronaTools/taxonomy \
&& cd /Krona/KronaTools \
&& ./install.pl \
&& ./updateTaxonomy.sh

