FROM debian:buster

RUN apt-get update \ 
&& apt-get install -y python3 python3-dev python3-pip \
&& apt-get install -y wget unzip \ 
&& pip3 --no-cache-dir install requests scipy numpy pandas \
&& wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2020-05-01.zip \
&& unzip taxdmp_2020-05-01.zip \
&& largestTax=`sort -t't' -k1nr names.dmp | head -1 | cut -f1` \
&& tomidaeTax=$((largestTax+1)) \
&& /bin/echo -e "$tomidaeTax\t|\tMycobacterium tomidae\t|\t\t|\tscientific name\t|" >> names.dmp \
&& mv names.dmp /home \
&& rm taxdmp_2020-05-01.zip *.dmp *.prt

### Software Versions ###

RUN env | grep "pengu_software_version" | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt

RUN if [ -d "/.singularity.d/env" ] ; \
then grep "pengu_software_version" /.singularity.d/env/* | awk '{print $2}' | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt ; \
fi

RUN pip3 freeze >> /etc/pengu_software_version.txt

