FROM debian:buster

RUN apt-get update \ 
&& apt-get install -y python3 python3-dev python3-pip \
&& pip3 --no-cache-dir install requests scipy numpy pandas
 
### Software Versions ###

RUN env | grep "pengu_software_version" | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt

RUN if [ -d "/.singularity.d/env" ] ; \
then grep "pengu_software_version" /.singularity.d/env/* | awk '{print $2}' | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt ; \
fi

RUN pip3 freeze >> /etc/pengu_software_version.txt

