#!/usr/bin/env python3

import pandas as pd
import numpy as np
import math

def buildMatrix():

    df = pd.read_csv('mash.txt', header =None, sep='\t')
    iniArray = df.to_numpy()

    numFastas = math.sqrt(len(iniArray))    
    colList = np.split(iniArray[:,2], numFastas)   

    mashMatrix = np.vstack(colList)

if __name__ == "__main__":

    buildMatrix()
